FROM ruby
LABEL maintainer='Mario David <mariojmdavid@gmail.com>'

RUN apt-get update && apt-get install -y --no-install-recommends \
        apt-utils \
        cmake \
        gcc \
        git && \
    apt-get autoremove -y && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

RUN gem install licensee
